# GitHub Action para gerar a animação da cobra (versão final e corrigida)

name: Generate Snake

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v3

      # 2. Cria a pasta 'dist' para garantir que ela exista antes de ser usada
      - name: Create dist directory
        run: mkdir -p dist

      # 3. Gera a animação da cobra DENTRO da pasta 'dist'
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Especifica o caminho de saída completo
          svg_out_path: dist/snake.svg

      # 4. Envia o CONTEÚDO da pasta 'dist' para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
