# GitHub Action para gerar a animação da cobra

name: Generate Snake

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v3

      # Cria a pasta 'dist' para garantir que ela exista
      - name: Create dist directory
        run: mkdir -p dist

      # Gera a animação da cobra
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Gera o arquivo SVG com o nome 'snake.svg' dentro da pasta dist
          svg_out_path: dist/snake.svg

      # Envia os arquivos gerados para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
